spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/productdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
