spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventorydb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092